version: '3'
volumes:
  dados:
services: 
  db: 
    image: postgres:9.6
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      #- dados:/var/lib/postgresql/data
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  web:
    image: nginx:1.13
    volumes:
      - ./web:/usr/share/nginx/html
    ports:
      - 81:81